# Coding exercises
Exercises 1-3 are thought exercises that don't require coding. If you need a Python crash-course/refresher, work through the [`python_101.ipynb`](./python_101.ipynb) notebook in chapter 1.

## Exercise 4: Generate the data by running this cell
This will give you a list of numbers to work with in the remaining exercises.

In [1]:
import random

random.seed(0)
salaries = [round(random.random()*1000000, -3) for _ in range(100)]

## Exercise 5: Calculating statistics and verifying
### mean

In [2]:
mean = sum(salaries) / len(salaries)
mean

585690.0

### median

In [3]:
median = sorted(salaries)[len(salaries)//2 if len(salaries) % 2 != 0 else (len(salaries)//2 - 1 + len(salaries)//2) // 2]
median

588000.0

### mode

In [4]:
from collections import Counter
mode = Counter(salaries).most_common(1)[0][0]
mode

477000.0

### sample variance
Remember to use Bessel's correction.

In [5]:
sample_var = (sum((x - mean) ** 2 for x in salaries) / (len(salaries) - 1)) 
sample_var

70664054444.44444

### sample standard deviation
Remember to use Bessel's correction.

In [6]:
sample_sd = (sum((x - mean) ** 2 for x in salaries) / (len(salaries) - 1)) ** 0.5
sample_sd

265827.11382484

## Exercise 6: Calculating more statistics
### range

In [18]:
range = max(salaries) - min(salaries)
range

995000.0

### coefficient of variation
Make sure to use the sample standard deviation.

In [8]:
coef_var = sample_sd // mean
coef_var

0.0

### interquartile range

In [9]:
import numpy as np
q1, q3 = np.quantile(salaries, [0.25, 0.75], method='linear') 
inter_quartile_range = q3 - q1

### quartile coefficent of dispersion

In [10]:
quartile_cof_dispersion = inter_quartile_range / q1 + q3
quartile_cof_dispersion

816751.0241635687

## Exercise 7: Scaling data
### min-max scaling

In [11]:
import numpy as np
mm_normalized_salaries = (salaries - np.min(salaries)) / range
mm_normalized_salaries

array([0.84723618, 0.76080402, 0.42211055, 0.25929648, 0.51256281,
       0.40603015, 0.78693467, 0.30351759, 0.47839196, 0.58492462,
       0.91155779, 0.50653266, 0.28241206, 0.75879397, 0.6201005 ,
       0.25125628, 0.91356784, 0.98693467, 0.81306533, 0.90552764,
       0.31055276, 0.73266332, 0.90251256, 0.68643216, 0.47336683,
       0.10050251, 0.43517588, 0.61306533, 0.91658291, 0.97085427,
       0.47839196, 0.86834171, 0.26030151, 0.8080402 , 0.55075377,
       0.01306533, 0.72261307, 0.4       , 0.8281407 , 0.67035176,
       0.        , 0.49547739, 0.87135678, 0.24422111, 0.32562814,
       0.87336683, 0.19095477, 0.56984925, 0.23919598, 0.9718593 ,
       0.80603015, 0.44924623, 0.07939698, 0.32060302, 0.50954774,
       0.93668342, 0.10854271, 0.55276382, 0.70954774, 0.54874372,
       0.81708543, 0.54170854, 0.9678392 , 0.60502513, 0.58994975,
       0.44623116, 0.59798995, 0.38592965, 0.57788945, 0.29045226,
       0.18894472, 0.18693467, 0.61507538, 0.65929648, 0.47839

### standardizing

In [13]:
normalized_salaries = (salaries - np.array(mean)) / sample_sd
normalized_salaries

array([ 0.97172179,  0.64820325, -0.61953801, -1.22895665, -0.28097209,
       -0.6797275 ,  0.74601118, -1.06343554, -0.40887477, -0.01011936,
        1.21247978, -0.30354315, -1.14243425,  0.64067957,  0.12154516,
       -1.2590514 ,  1.22000347,  1.49461804,  0.84381912,  1.18990872,
       -1.03710263,  0.54287164,  1.17862319,  0.36982683, -0.42768399,
       -1.82332793, -0.57063404,  0.09521226,  1.231289  ,  1.43442854,
       -0.40887477,  1.05072051, -1.22519481,  0.8250099 , -0.13802204,
       -2.15060831,  0.5052532 , -0.70229856,  0.90024677,  0.30963734,
       -2.19951228, -0.34492343,  1.06200604, -1.28538431, -0.98067498,
        1.06952973, -1.48476201, -0.06654701, -1.30419352,  1.43819039,
        0.81748621, -0.51796823, -1.90232664, -0.9994842 , -0.29225762,
        1.30652587, -1.79323318, -0.13049835,  0.45634923, -0.14554572,
        0.85886649, -0.17187863,  1.42314301,  0.06511751,  0.00868986,
       -0.52925376,  0.03878461, -0.75496437, -0.03645226, -1.11

## Exercise 8: Calculating covariance and correlation
### covariance

In [19]:
import numpy as np
cov_matrix = np.cov(mm_normalized_salaries, normalized_salaries)
cov_matrix

array([[0.07137603, 0.26716293],
       [0.26716293, 1.        ]])

### Pearson correlation coefficient ($\rho$)

In [22]:
mm_sd, n_sd = np.std(mm_normalized_salaries, ddof=1), np.std(normalized_salaries, ddof=1)
corr = cov_matrix / (mm_sd * n_sd)
corr

array([[0.26716293, 1.        ],
       [1.        , 3.74303428]])

<hr>
<div style="overflow: hidden; margin-bottom: 10px;">
    <div style="float: left;">
        <a href="./python_101.ipynb">
            <button>Python 101</button>
        </a>
    </div>
    <div style="float: right;">
        <a href="../../solutions/ch_01/solutions.ipynb">
            <button>Solutions</button>
        </a>
        <a href="../ch_02/1-pandas_data_structures.ipynb">
            <button>Chapter 2 &#8594;</button>
        </a>
    </div>
</div>
<hr>